# Generated by Django 5.1 on 2024-08-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='homes',
        ),
    ]
